language: c

sudo: required
dist: trusty

os:
 - linux

compiler:
 - gcc

addons:
 apt:
  packages:
   - liblmdb0
   - liblmdb-dev
   - libhttp-parser2.1
   - libhttp-parser-dev

script:
 - make
 - make counter-test-lmdb
